language: python

python:
  - '2.7'

install: echo "Do nothing for install step"
script: echo "No tests, just deploy!"

deploy:
  provider: pypi
  user: FlorianKempenich
  password:
    secure: WURxVXy2k3MgMhtK48kI+wZ77gmfv0nocTWiMhBA1FjnoMd+YRGDDZW2dlboJxYmmpkED2KbBdOamenvOCApL2Uan1v0TP05Hw0c1gskVI7HQBkqGxd/3Zllx4K37FdJwl3Utv4dWPIPUa+VUYEPP41iLO0LR1AqdfbW1Ccy7bP8A8HGdW40N7ZrgGMMcWGttXOsiK9M1zpBrQt1ooM/0JsSvgKoQ+mUmrv477YV1QLdSzFlmqJPu1fjJQL/TB5rgyObSJrc+EXyubvT0ob+VWrhNcKwanDRyVjzT6gIyBYM9/6YJPvFumhHsS9wakx02+JX1S2gC7B1AMGHk9gIisUneYB2OOlymF/8LXXAe0goWyc93D1DZ7hOEyOiB9+22BnniLgU61hvm8QvHmfyPzNm8HV2VMhSAzobhcMtlcD1ZHWZhDNnWGoqlqNOX9L1NDBgo05NcLFMCxjNs2tUXUP2+mVVsoJDLAf1/KxgY3D4R82r8DyUleX5vGvynr/lGDBK3Ofu/WHRY3i/YdlfcxxQwMLi8UBBvcLuoe0WFIxnuBTo3p3c9WhWfyIY1yl9z5ixlDW5A2peCJeYePegM0BPYJeopJOMAq8QQJpEv0bqCsBoQtRtJlYtcpjPkGEdOHqdFHRLa7K9OUbEUpONuBlg1JPNu5MdDvc45th7nTc=
